pointers: pointers.o
	g++ -o pointers pointers.o

pointers.o: pointers.cpp
	g++ -c pointers.cpp

pointers_and_arrays: pointers_and_arrays.o
	g++ -o pointers_and_arrays pointers_and_arrays.o

pointers_and_arrays.o: pointers_and_arrays.cpp
	g++ -c pointers_and_arrays.cpp